### ISSUE TITLE
Implement a Mock to test the connection with Silk

### ISSUE THREAD

**Issue by luigiselmi** [LiDaKrA/FuhSen-reactive#4]
The test should send to the mock a request like

curl http://localhost:9000/ldw/restApiWrapper/id/twitter/search?query=merkel

in the class that is used for the connection. The mock must return the json data from the file built from the request above so that there will be no need to make a real connection. The test must work with Sbt. A mock framework like http://scalamock.org/ should work fine.

**Comment by collarad** [comment]
Done!!!
